<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPxLidOZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPxLidOZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPxLidOZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPxLidOZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPxLidOZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PxLidOZ',
    'container.build_id' => '425903f3',
    'container.build_time' => 1585824654,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPxLidOZ');
