<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6JcP4VS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6JcP4VS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6JcP4VS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6JcP4VS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6JcP4VS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6JcP4VS',
    'container.build_id' => '47885827',
    'container.build_time' => 1591279709,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6JcP4VS');
