<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZsNWPuE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZsNWPuE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZsNWPuE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZsNWPuE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZsNWPuE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZsNWPuE',
    'container.build_id' => 'f176716e',
    'container.build_time' => 1591614697,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZsNWPuE');
